Firebase push messaging implementation
Let-s-build-something/Communication-enrichment pull request #3
Opened 2024-09-11 11:23 UTC by JacobCube

See the task here: https://app.clickup.com/t/86c0994nb

2024-09-11 11:23 UTC, JacobCube commented
Task linked: [CU-86c0994nb Push notifications support - FE](https://app.clickup.com/t/86c0994nb)

2024-09-12 16:05 UTC, zeddosx requested changes

2024-09-12 16:05 UTC, zeddosx commented on composeApp/src/androidMain/kotlin/chat/enrichment/eu/MainActivity.kt
> +        }
Eeew brother

2024-09-12 16:05 UTC, zeddosx commented on composeApp/src/androidMain/kotlin/chat/enrichment/eu/fcm/GeneralFirebaseMessagingService.kt
> +
eeew delete this, noo need for 2 empty lines

2024-09-12 16:05 UTC, zeddosx commented on composeApp/src/commonMain/kotlin/ui/account/AccountDashboardScreen.kt
> +
eeew

2024-09-12 16:09 UTC, JacobCube commented on composeApp/src/androidMain/kotlin/chat/enrichment/eu/MainActivity.kt
> +        }
that stays, it can implemented later if needed, this is just a point to it

2024-09-12 16:12 UTC, zeddosx reviewed
lgtm iykyk

2024-09-12 16:15 UTC, merged